[project]
name = "bllind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
    "transformers>=4.49.0",
]

[tool.ruff]
indent-width = 2
